import * as fs from 'node:fs';
import * as path from 'node:path';
import { config } from '../config';
import {
  PageManifest,
  sanitizeIteration,
  sanitizeProject,
} from './page.types';

// 上传时用户可通过 query 传入的覆盖参数（全部可选）
export interface ManifestOverrides {
  id?: string;
  title?: string;
  project?: string;
  iteration?: string;
  version?: string;
  author?: string;
  tags?: string[];
  summary?: string;
}

// 自动解析结果
export interface ResolvedManifest {
  manifest: PageManifest;
  // 是否通过自动推断生成（非用户提供）
  autoGenerated: boolean;
}

function isSafeManifestPath(value: string): boolean {
  if (!value || value.includes('\0')) return false;
  if (/^[a-zA-Z]:/.test(value)) return false;
  if (path.isAbsolute(value) || path.win32.isAbsolute(value) || path.posix.isAbsolute(value)) return false;
  const normalized = path.posix.normalize(value.replace(/\\/g, '/'));
  if (!normalized || normalized === '.' || normalized.startsWith('/')) return false;
  if (normalized.startsWith('..') || normalized.includes('/../')) return false;
  return true;
}

function resolveSafeFile(rootDir: string, relPath: string, field: string): string {
  if (!isSafeManifestPath(relPath)) {
    throw new Error(`${field} 路径不合法：${relPath}`);
  }

  const abs = path.resolve(rootDir, relPath);
  const root = path.resolve(rootDir);
  if (!abs.startsWith(root + path.sep) && abs !== root) {
    throw new Error(`${field} 路径越界：${relPath}`);
  }

  if (!fs.existsSync(abs)) {
    throw new Error(`${field} 文件不存在：${relPath}`);
  }
  return abs;
}

/**
 * 智能查找入口 HTML：
 *  1. 若 manifest 指定了 entry 且合法 → 直接用
 *  2. 否则按优先级查找：index.html → index.htm → main.html → report.html
 *  3. 再兜底找根目录第一个 .html
 */
function resolveEntry(rootDir: string, manifestEntry?: string): string {
  if (manifestEntry) {
    const abs = resolveSafeFile(rootDir, manifestEntry, 'entry');
    if (!abs.toLowerCase().endsWith('.html') && !abs.toLowerCase().endsWith('.htm')) {
      throw new Error(`entry 不是 HTML 文件：${manifestEntry}`);
    }
    return manifestEntry;
  }

  const priority = ['index.html', 'index.htm', 'main.html', 'report.html'];
  for (const name of priority) {
    if (fs.existsSync(path.join(rootDir, name))) {
      return name;
    }
  }

  const files = fs.readdirSync(rootDir);
  const htmlFile = files.find(f => f.toLowerCase().endsWith('.html') || f.toLowerCase().endsWith('.htm'));
  if (htmlFile) return htmlFile;

  throw new Error('未找到入口 HTML 文件（index.html / main.html / *.html）');
}

/**
 * 宽松模式：从目录自动推断 manifest。
 *  - 查找入口 HTML
 *  - 解析 <title>
 *  - 生成 id、填充 project/iteration 等
 */
function inferFromDirectory(
  dir: string,
  overrides: ManifestOverrides,
  originalName: string,
): { manifest: PageManifest; autoGenerated: boolean } {
  const entry = resolveEntry(dir);
  const entryAbs = path.join(dir, entry);

  // 尝试读取 <title>
  let title = '';
  try {
    const html = fs.readFileSync(entryAbs, 'utf-8');
    const match = html.match(/<title>(.*?)<\/title>/i);
    if (match) title = match[1].trim();
  } catch {
    // ignore
  }

  // 基础信息
  const now = new Date().toISOString();
  const inferredProject = sanitizeProject(
    overrides.project || undefined,
    'uncategorized',
  );
  const inferredIteration = sanitizeIteration(
    overrides.iteration || undefined,
    new Date().toISOString().slice(0, 7), // YYYY-MM
  );

  const manifest: PageManifest = {
    schema_version: '1.0',
    id: overrides.id || `page_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`,
    title: overrides.title || title || path.basename(originalName, path.extname(originalName)) || '未命名页面',
    project: inferredProject,
    iteration: inferredIteration,
    version: overrides.version,
    author: overrides.author,
    tags: overrides.tags,
    summary: overrides.summary,
    created_at: now,
    entry,
  };

  return { manifest, autoGenerated: true };
}

export const ManifestResolver = {
  /**
   * 解析/推断 manifest.json。
   *
   * 流程：
   *  1. 若目录存在合法 manifest.json → 走标准校验
   *  2. 否则走宽松推断模式
   */
  resolve(
    dir: string,
    overrides: ManifestOverrides = {},
    originalName: string = 'upload.zip',
  ): ResolvedManifest {
    const manifestPath = path.join(dir, 'manifest.json');

    if (fs.existsSync(manifestPath)) {
      // 标准模式：校验 manifest.json
      let raw: any;
      try {
        const content = fs.readFileSync(manifestPath, 'utf-8');
        raw = JSON.parse(content);
      } catch {
        throw new Error('manifest.json 解析失败（JSON 格式错误）');
      }

      // 应用 overrides（覆盖/补充字段）
      if (overrides.id) raw.id = overrides.id;
      if (overrides.title) raw.title = overrides.title;
      if (overrides.project) raw.project = overrides.project;
      if (overrides.iteration) raw.iteration = overrides.iteration;
      if (overrides.version) raw.version = overrides.version;
      if (overrides.author) raw.author = overrides.author;
      if (overrides.tags) raw.tags = overrides.tags;
      if (overrides.summary) raw.summary = overrides.summary;

      const { validateManifest } = require('./page.types');
      const manifest = validateManifest(raw);
      manifest.entry = resolveEntry(dir, manifest.entry);
      return { manifest, autoGenerated: false };
    }

    // 宽松模式：自动推断
    if (!config.compat.allowMissingManifest) {
      throw new Error('manifest.json 不存在，且未开启宽松模式');
    }
    return inferFromDirectory(dir, overrides, originalName);
  },

  /** 将 manifest 写回目录（供自动推断后回写） */
  writeManifest(dir: string, manifest: PageManifest): void {
    const target = path.join(dir, 'manifest.json');
    fs.writeFileSync(target, JSON.stringify(manifest, null, 2), 'utf-8');
  },
};
